//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using System;

    public partial class CT_HOADON
    {
        public string MaHoaDon { get; set; }
        public string MaPhieuDatPhong { get; set; }
        public int? ThanhTien { get; set; }

        public virtual HOADON HOADON { get; set; }
        public virtual PHIEUDATPHONG PHIEUDATPHONG { get; set; }
    }
}
