//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;

    public partial class CT_PHIEUHANGHOA : BaseViewModel
    {
        public CT_PHIEUHANGHOA()
        {

        }

        public CT_PHIEUHANGHOA(HANGHOA hh)
        {
            HANGHOA = hh;
            MaHangHoa = hh.MaHangHoa;
        }

        private int _stt;
        public int STT
        {
            get { return _stt; }
            set { _stt = value; OnPropertyChanged(); }
        }

        private string _maPhieuSuDung;
        public string MaPhieuSuDung
        {
            get { return _maPhieuSuDung; }
            set { _maPhieuSuDung = value; OnPropertyChanged(); }
        }

        private string _maHangHoa;
        public string MaHangHoa
        {
            get { return _maHangHoa; }
            set { _maHangHoa = value; OnPropertyChanged(); }
        }

        private short? _soLuong;
        public short? SoLuong
        {
            get { return _soLuong; }
            set { _soLuong = value; OnPropertyChanged(); }
        }

        private int? _donGia;
        public int? DonGia
        {
            get { return _donGia; }
            set { _donGia = value; OnPropertyChanged(); }
        }

        private int? _thanhTien;
        public int? ThanhTien
        {
            get { return _thanhTien; }
            set { _thanhTien = value; OnPropertyChanged(); }
        }

        private string _trangThai;
        public string TrangThai
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); }
        }

        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUSUDUNG PHIEUSUDUNG { get; set; }
    }
}
