//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUHANGHOA
    {
        public int MaPhieu { get; set; }
        public int MaHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual PHIEUSUDUNG PHIEUSUDUNG { get; set; }
    }
}
