//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;

    public partial class DICHVU : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.CT_PHIEUDICHVU = new HashSet<CT_PHIEUDICHVU>();
        }

        public DICHVU(string maDichVu, string tenDichVu, int? donGia, ICollection<CT_PHIEUDICHVU> cT_PHIEUDICHVU)
        {
            MaDichVu = maDichVu;
            TenDichVu = tenDichVu;
            DonGia = donGia;
            CT_PHIEUDICHVU = cT_PHIEUDICHVU;
        }

        private int _stt;
        public int STT
        {
            get { return _stt; }
            set { _stt = value; OnPropertyChanged(); }
        }

        private string _maDichVu;
        public string MaDichVu
        {
            get { return _maDichVu; }
            set { _maDichVu = value; OnPropertyChanged(); }
        }

        private string _tenDichVu;
        public string TenDichVu
        {
            get { return _tenDichVu; }
            set { _tenDichVu = value; OnPropertyChanged(); }
        }

        private string _donViTinh;
        public string DonViTinh
        {
            get { return _donViTinh; }
            set { _donViTinh = value; OnPropertyChanged(); }
        }

        private int? _donGia;
        public int? DonGia
        {
            get { return _donGia; }
            set { _donGia = value; OnPropertyChanged(); }
        }

        private string _trangThai;
        public string TrangThai
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDICHVU> CT_PHIEUDICHVU { get; set; }
    }
}
