//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class KHACHHANG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }

        private string _character;
        public string Character 
        {
            get { return _character; }
            set { _character = value; OnPropertyChanged(); } 
        }

        private Brush _bgColor;
        public Brush BgColor 
        {
            get { return _bgColor; } 
            set { _bgColor = value; OnPropertyChanged(); } 
        }
        
        private string _stt;
        public string STT 
        {
            get { return _stt; }
            set { _stt = value; OnPropertyChanged(); } 
        }
        private string _maKhachHang;
        public string MaKhachHang 
        {
            get { return _maKhachHang; }
            set { _maKhachHang = value; OnPropertyChanged(); } 
        }

        private string _tenKhachHang;
        public string TenKhachHang 
        {
            get { return _tenKhachHang; }
            set { _tenKhachHang = value; OnPropertyChanged(); } 
        }

        private string _CCCD;
        public string CCCD 
        {
            get { return _CCCD; }
            set { _CCCD = value; OnPropertyChanged(); } 
        }

        private string _gioiTinh;
        public string GioiTinh 
        {
            get { return _gioiTinh; } 
            set { _gioiTinh = value; OnPropertyChanged(); } 
        }

        private DateTime? _ngaySinh;
        public DateTime? NgaySinh 
        {
            get { return _ngaySinh; }
            set { _ngaySinh = value; OnPropertyChanged(); } 
        }
        
        private string _soDienThoai;
        public string SoDienThoai 
        {
            get { return _soDienThoai; } 
            set { _soDienThoai = value; OnPropertyChanged(); } 
        }

        private string _loaiKhachHang;
        public string LoaiKhachHang 
        {
            get { return _loaiKhachHang; }
            set { _loaiKhachHang = value; OnPropertyChanged(); } 
        }

        private string _trangThai;
        public string TrangThai 
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); } 
        }

        private bool _isLastRow;
        public bool IsLastRow 
        {
            get { return _isLastRow; }
            set { _isLastRow = value; OnPropertyChanged(); } 
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
    }
}
