//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class KHACHHANG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }

        private string _stt;
        private string _maKhachHang;
        private string _tenKhachHang;
        private string _CCCD;
        private string _gioiTinh;
        private Nullable<System.DateTime> _ngaySinh;
        private string _soDienThoai;
        private string _loaiKhachHang;
        private string _trangThai;
        private bool _isLastRow;

        public string Character { get; set; }
        public Brush BgColor { get; set; }
        public string STT { get => _stt; set { _stt = value; OnPropertyChanged(); } }
        public string MaKhachHang { get => _maKhachHang; set { _maKhachHang = value; OnPropertyChanged(); } }
        public string TenKhachHang { get => _tenKhachHang; set { _tenKhachHang = value; OnPropertyChanged(); } }
        public string CCCD { get => _CCCD; set { _CCCD = value; OnPropertyChanged(); } }
        public string GioiTinh { get => _gioiTinh; set { _gioiTinh = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> NgaySinh { get => _ngaySinh; set { _ngaySinh = value; OnPropertyChanged(); } }
        public string SoDienThoai { get => _soDienThoai; set { _soDienThoai = value; OnPropertyChanged(); } }
        public string LoaiKhachHang { get => _loaiKhachHang; set { _loaiKhachHang = value; OnPropertyChanged(); } }
        public string TrangThai { get => _trangThai; set { _trangThai = value; OnPropertyChanged(); } }
        public bool IsLastRow { get => _isLastRow; set { _isLastRow = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
    }
}
