//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;

    public partial class PHIEUSUDUNG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUSUDUNG()
        {
            this.CT_PHIEUDICHVU = new HashSet<CT_PHIEUDICHVU>();
            this.CT_PHIEUHANGHOA = new HashSet<CT_PHIEUHANGHOA>();
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }

        private string _maPhieuSuDung;
        public string MaPhieuSuDung
        {
            get { return _maPhieuSuDung; }
            set { _maPhieuSuDung = value; OnPropertyChanged(); }
        }

        private int? _triGia;
        public int? TriGia
        {
            get { return _triGia; }
            set { _triGia = value; OnPropertyChanged(); }
        }

        private DateTime? _ngayLap;
        public DateTime? NgayLap
        {
            get { return _ngayLap; }
            set { _ngayLap = value; OnPropertyChanged(); }
        }

        private string _trangThai;
        public string TrangThai
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDICHVU> CT_PHIEUDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUHANGHOA> CT_PHIEUHANGHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
    }
}
