//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using Hotel_Management_System.ViewModel;
    using Hotel_Management_System.ViewModel.Other;
    using System;
    using System.Collections.Generic;

    public partial class PHONG : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.PHIEUDATPHONGs = new HashSet<PHIEUDATPHONG>();
        }

        public PHONG(string maPhong, string maLoaiPhong, string trangThai, string ghiChu, LOAIPHONG lOAIPHONG, ICollection<PHIEUDATPHONG> pHIEUDATPHONGs)
        {
            _maPhong = maPhong;
            _maLoaiPhong = maLoaiPhong;
            _trangThai = trangThai;
            _ghiChu = ghiChu;
            LOAIPHONG = lOAIPHONG;
            PHIEUDATPHONGs = pHIEUDATPHONGs;
        }

        private string _maPhong;
        public string MaPhong
        {
            get { return _maPhong; }
            set { _maPhong = value; OnPropertyChanged(); }
        }

        private string _maLoaiPhong;
        public string MaLoaiPhong
        {
            get { return _maLoaiPhong; }
            set { _maLoaiPhong = value; OnPropertyChanged(); }
        }

        private string _trangThai;
        public string TrangThai
        {
            get { return _trangThai; }
            set { _trangThai = value; OnPropertyChanged(); }
        }

        private string _ghiChu;
        public string GhiChu
        {
            get { return _ghiChu; }
            set { _ghiChu = value; OnPropertyChanged(); }
        }

        private string _stateColor;
        public string StateColor
        {
            get { return _stateColor; }
            set { _stateColor = value; OnPropertyChanged(); }
        }

        public virtual LOAIPHONG LOAIPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATPHONG> PHIEUDATPHONGs { get; set; }
    }
}
