//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System.Model
{
    using System;

    public partial class THONGKE
    {
        public string MaThongKe { get; set; }
        public string MaLoaiPhong { get; set; }
        public DateTime? NgayLap { get; set; }
        public double? DoanhThu { get; set; }
        public double? TiLe { get; set; }

        public virtual LOAIPHONG LOAIPHONG { get; set; }
    }
}
