CREATE DATABASE QL_KS
GO
USE QL_KS
GO

CREATE TABLE THONGKE (
	MaThongKe INT PRIMARY KEY,
    MaLoaiPhong INT,
    ThoiGian DATE,
	DoanhThu FLOAT,
    TiLe FLOAT,
)


CREATE TABLE HOADON (
    MaHoaDon INT PRIMARY KEY,
    MaNhanVien INT,
	MaKhachHang INT,
    TriGia FLOAT,
    NgayLap DATE
)


GO
CREATE TABLE KHACHHANG (
    MaKhachHang INT PRIMARY KEY,
    TenKhachHang NVARCHAR(50),
    CCCD NVARCHAR(20),
    GioiTinh NVARCHAR(10),
    NgaySinh DATE,
    SDT NVARCHAR(20),
    Email NVARCHAR(50)
)
GO

INSERT INTO KHACHHANG VALUES (1, N'Huỳnh Tiến Phát', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (2, N'Huỳnh Tiến Phát', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (3, N'Nguyễn Trương Bảo Duy', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (4, N'Nguyễn Phước Thiện', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (5, N'Phan Thành Phúc', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (6, N'Trần Tiến Phát', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')
INSERT INTO KHACHHANG VALUES (7, N'Huỳnh Tiến Phát', N'12345678', N'Nam', '2003/9/24', N'0362123456', N'2409huynhphat@gmail.com')

CREATE TABLE NHANVIEN (
    MaNhanVien INT PRIMARY KEY,
    TenNhanVien NVARCHAR(50),
    CCCD NVARCHAR(20),
    SDT NVARCHAR(20),
    BoPhan NVARCHAR(50),
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    idAccount INT
)
GO
CREATE TABLE CT_HOADON (
	MaHoaDon INT,
	MaPhieuDatPhong INT,
	ThanhTien FLOAT,
	PRIMARY KEY (MaHoaDon, MaPhieuDatPhong)
)
GO
CREATE TABLE PHIEUDATPHONG (
	MaPhieuDatPhong INT PRIMARY KEY,
	MaPhong INT,
	SoNguoi INT,
	NgayDen DATE,
	NgayDi DATE,
	TienCoc FLOAT,
	MaKhachHang INT
)

GO
CREATE TABLE PHIEUSUDUNG (
	MaPhieu INT PRIMARY KEY,
	MaPhieuDatPhong INT,
	TriGia FLOAT,
	NgayLap DATE
)
GO 
CREATE TABLE CT_PHIEUDICHVU (
	MaPhieu INT,
	MaDichVu INT,
	SoLuong INT,
	ThanhTien FLOAT,
	PRIMARY KEY (MaPhieu, MaDichVu) 
) 

GO
CREATE TABLE DICHVU (
	MaDichVu INT PRIMARY KEY,
	TenDichVu NVARCHAR(50),
	DonViTinh NVARCHAR(20),
	DonGia FLOAT
)
GO
CREATE TABLE CT_PHIEUHANGHOA (
	MaPhieu INT,
	MaHangHoa INT,
	SoLuong INT,
	ThanhTien FLOAT,
	PRIMARY KEY (MaPhieu, MaHangHoa) 
)
GO
CREATE TABLE PHIEUNHAPHANG (
	MaPhieuNhapHang INT PRIMARY KEY,
	MaNhanVien INT,
	NgayLap DATE,
	TriGia FLOAT
)
GO 
CREATE TABLE CT_PHIEUNHAPHANG (
	MaPhieuNhapHang INT,
	MaHangHoa INT,
	SoLuong INT,
	ThanhTien FLOAT,
	PRIMARY KEY (MaPhieuNhapHang, MaHangHoa) 
)

GO 
CREATE TABLE HANGHOA (
	MaHangHoa INT PRIMARY KEY,
	TenHangHoa NVARCHAR(50),
	SLTonKho INT, 
	DonVITinh NVARCHAR (20),
	DonGiaBan FLOAT,
	DonGiaNhap FLOAT
)
GO 
CREATE TABLE PHONG (
	MaPhong INT PRIMARY KEY,
	MaLoaiPhong INT,
	TrangThai NVARCHAR (20),
	GhiChu NVARCHAR (50)
)

GO 
CREATE TABLE LOAIPHONG (
	MaLoaiPhong INT PRIMARY KEY,
	TenLoaiPhong NVARCHAR(50),
	DonGia FLOAT 
)
CREATE TABLE HE_THONG (
    idAccount INT PRIMARY KEY,
    username NVARCHAR(50),
    password NVARCHAR(50),
)
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang)
ALTER TABLE HOADON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_HT FOREIGN KEY (idAccount) REFERENCES HE_THONG(idAccount)
ALTER TABLE CT_HOADON ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHoaDon) REFERENCES HOADON (MaHoaDon)
ALTER TABLE CT_HOADON ADD CONSTRAINT FK_CTHD_PDP FOREIGN KEY (MaPhieuDatPhong) REFERENCES PHIEUDATPHONG (MaPhieuDatPhong)
ALTER TABLE PHIEUDATPHONG ADD CONSTRAINT FK_PDP_P FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
ALTER TABLE PHIEUDATPHONG ADD CONSTRAINT FK_PDP_KH FOREIGN KEY (MaPhong) REFERENCES KHAChHANG(MaKhachHang)
ALTER TABLE PHIEUSUDUNG ADD CONSTRAINT FK_PSD_PDP FOREIGN KEY (MaPhieuDatPhong) REFERENCES PHIEUDATPHONG (MaPhieuDatPhong)
ALTER TABLE CT_PHIEUNHAPHANG ADD CONSTRAINT FK_CTPNH_HH FOREIGN KEY (MaHangHoa) REFERENCES HANGHOA(MaHangHoa)
ALTER TABLE CT_PHIEUNHAPHANG ADD CONSTRAINT FK_CTPNH_PNH FOREIGN KEY (MaPhieuNhapHang) REFERENCES PHIEUNHAPHANG(MaPhieuNhapHang)
ALTER TABLE PHONG ADD CONSTRAINT FK_P_LP FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG (MaLoaiPhong)
ALTER TABLE PHIEUNHAPHANG ADD CONSTRAINT FK_PNH_NV FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien)
ALTER TABLE CT_PHIEUHANGHOA ADD CONSTRAINT FK_CTPHH_PSD FOREIGN KEY (MaPhieu) REFERENCES PHIEUSUDUNG(MaPhieu)
ALTER TABLE CT_PHIEUHANGHOA ADD CONSTRAINT FK_CTPHH_HH FOREIGN KEY (MaHangHoa) REFERENCES HANGHOA(MaHangHoa)
ALTER TABLE CT_PHIEUDICHVU ADD CONSTRAINT FK_CTPDV_DV FOREIGN KEY (MaDichVu) REFERENCES DICHVU(MaDichVu)
ALTER TABLE CT_PHIEUDICHVU ADD CONSTRAINT FK_CTPDV_PSD FOREIGN KEY (MaPhieu) REFERENCES PHIEUSUDUNG(MaPhieu)
ALTER TABLE THONGKE ADD CONSTRAINT FK_TK_LP FOREIGN KEY (MaLoaiPhong) REFERENCES LOAIPHONG(MaLoaiPhong)

INSERT INTO HE_THONG (idAccount, username, password)
VALUES 
    (1, 'user1', 'pass1'),
    (2, 'user2', 'pass2'),
    (3, 'user3', 'pass3'),
    (4, 'user4', 'pass4'),
    (5, 'user5', 'pass5');
